_wandb:
    value:
        cli_version: 0.22.1
        e:
            3mxvg5j45s5fyjwe0q209zmgsajpxsby:
                args:
                    - --cv
                    - "true"
                    - --half_precision
                    - "true"
                    - --log_to_wandb
                    - "true"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "211116445696"
                        used: "75164516352"
                email: macyvesdylan@gmail.com
                executable: /home/dylan-kmutt/ubpd/.venv/bin/python3
                git:
                    commit: d639f61efcf014fd44b46dea5404df8797eaf5d7
                    remote: https://github.com/Dylanyves/UBPD.git
                gpu: Tesla V100-SXM2-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-SXM2-16GB
                      uuid: GPU-cbe8447a-e054-9c16-e42f-1ab952539e8c
                host: pytorch-v100-instance
                memory:
                    total: "31557115904"
                os: Linux-5.10.0-35-cloud-amd64-x86_64-with-glibc2.31
                program: /home/dylan-kmutt/ubpd/main.py
                python: CPython 3.10.16
                root: /home/dylan-kmutt/ubpd
                startedAt: "2025-10-07T17:47:54.861153Z"
                writerId: 3mxvg5j45s5fyjwe0q209zmgsajpxsby
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.16
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_size:
    value: 16
criterion:
    value: ce
cv:
    value: true
device:
    value: cuda
early_stopping:
    value: true
fold:
    value: 1
half_precision:
    value: true
learning_rate:
    value: 0.001
log_to_wandb:
    value: true
max_epoch:
    value: 100
model_type:
    value: unet
optimizer:
    value: adamw
patience:
    value: 10
scheduler:
    value: rrlonp
seed:
    value: 42
